nodeLinker: node-modules
enableGlobalCache: false

packageExtensions:
  "@callstack/react-theme-provider@*":
    peerDependencies:
      react: "^19.0.0"
      react-dom: "^19.0.0"
  "@testing-library/react-hooks@*":
    peerDependencies:
      react: "^19.0.0"
      react-dom: "^19.0.0"
      "@types/react": "*"