enableGlobalCache: false
yarnPath: .yarn/releases/yarn-4.9.2.cjs

logFilters:
  - code: YN0060
    level: discard
    text: "@callstack/react-theme-provider"
  - code: YN0069
    level: discard
    text: "@callstack/react-theme-provider"
  - code: YN0086
    level: discard
    text: peer dependencies are incorrectly met
  - code: YN0000
    level: discard
    text: "dynastyweb@workspace:."

nodeLinker: node-modules

packageExtensions:
  "@callstack/react-theme-provider@*":
    peerDependencies:
      react: "*"
