export const getAuth = jest.fn(() => ({}));
export const onAuthStateChanged = jest.fn();
export const signInWithEmailAndPassword = jest.fn();
export const createUserWithEmailAndPassword = jest.fn();
export const signOut = jest.fn();
export const sendEmailVerification = jest.fn();
export const sendPasswordResetEmail = jest.fn();
export const updateProfile = jest.fn();
export const updateEmail = jest.fn();
export const updatePassword = jest.fn();
export const EmailAuthProvider = jest.fn();
export const reauthenticateWithCredential = jest.fn();
export const setPersistence = jest.fn(() => Promise.resolve());
export const browserLocalPersistence = {};
export const GoogleAuthProvider = jest.fn();
export const signInWithPopup = jest.fn();
export const RecaptchaVerifier = jest.fn();
export const signInWithPhoneNumber = jest.fn();
export const connectAuthEmulator = jest.fn();