name: Mobile App Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/mobile-test.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/mobile-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      
      - name: Install dependencies
        run: |
          cd apps/mobile
          yarn install --frozen-lockfile
      
      - name: Run linter
        run: |
          cd apps/mobile
          yarn lint
      
      - name: Run TypeScript check
        run: |
          cd apps/mobile
          yarn tsc --noEmit
      
      - name: Run tests
        run: |
          cd apps/mobile
          yarn test --ci --coverage --maxWorkers=2
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./apps/mobile/coverage
          flags: mobile
          name: mobile-coverage
          fail_ci_if_error: false

  test-ios:
    runs-on: macos-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      
      - name: Install dependencies
        run: |
          cd apps/mobile
          yarn install --frozen-lockfile
      
      - name: Install Pods
        run: |
          cd apps/mobile/ios
          pod install
      
      - name: Run tests
        run: |
          cd apps/mobile
          yarn test --ci

  test-android:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Install dependencies
        run: |
          cd apps/mobile
          yarn install --frozen-lockfile
      
      - name: Run tests
        run: |
          cd apps/mobile
          yarn test --ci